### ISSUE TITLE
RVO not working

### ISSUE THREAD

**Issue by coolmule0** [coolmule0/MYFLAMEGPU#2]
People not colliding properly, is this a maths issue?

**Comment by Robadob** [comment]
Had a quick look, not familiar enough with the actual formula of the model to provide any suggestion and I haven't really the time currently to sit down and decipher their paper.

I did however notice [this](https://github.com/coolmule0/MYFLAMEGPU/blob/Pedestrian/examples/Pedestrians/src/model/functions.c#L250) line.
`if (glm::length(relative_pos) < 0.0001)`

There's no reason you cant just compare them directly with.
`if (agent_pos==relative_pos)`

Unless you're changing the agents position between sending the message and that call, they should be byte for byte identical, so no shitty floating point differences. 

Unnecessarily calculating length is a bad idea. Involves an 'expensive' `sqrt`. If you're checking a fixed distance you're better off checking length squared ([`length2()`](https://glm.g-truc.net/0.9.4/api/a00188.html#ga1d8568485d8bbe6593dbbc2221659dfe)). Works fine for ordering and fixed distance comparisons (pre calc the sq length) and saves you a square root.

If you were infact attempting an equivalent of epislon equals, I'd suggest using the glm [`episolonEqual()`](http://glm.g-truc.net/0.9.8/api/a00163.html) methods. It returns a `bvec` though, so you'd need to wrap it in [`all()`](https://glm.g-truc.net/0.9.4/api/a00137.html#ga349edc1a383fff08c6d577428416a73b). That's *probably* cheaper than calculating length.
